### ISSUE TITLE
Machines in the robotics lab don't start connected/won't link to the r&d console

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#105]

**Comment by Repede** [comment]
In Polaris Code, machines in robotics do not need to be linked to the R&D Console (They won't show as linked by it). They have their own sync buttons when research is done and synced in the R&D Lab (And then Synced by the Robotics R&D Console) which will update their inventories.

So steps is simple: Scientists get research levels, then go in settings > Sync Database with Network.
Roboticist then goes in Robotics R&D Console and goes in settings > Sync Database with Network.
Roboticist then goes to a machine and presses Sync

They will now have the researched items.

![image](https://user-images.githubusercontent.com/5666820/51082183-40579100-16d0-11e9-8d18-fdbae3e7ef02.png)

![image](https://user-images.githubusercontent.com/5666820/51082187-49486280-16d0-11e9-848c-62474e6002b4.png)

**Comment by Repede** [comment]
Other note, there are two prosthetic fabricators almost next to each other in robotics, I don't know if that is intended or not.

![image](https://user-images.githubusercontent.com/5666820/51082205-89a7e080-16d0-11e9-8419-b2529cff6b3c.png)

**Comment by GeneriedJenelle** [comment]
This has been resolved.
