### ISSUE TITLE
Biopsy and Health scanners dont work on the Brute/burn surgery

### ISSUE THREAD

**Issue by reklaw9** [GeneriedJenelle/The-World-Server-Redux#1073]
#### Brief description of the issue
so, if you try to use the Biopsy scanner, or a health scanner, on the "Brute/Burn healing surgery" it wont work because the Code understands that you are trying to scan the patient non-surgically.

#### What you expected to happen
Do a incision then scan my patient using the biopsy scanner and do the brute healing surgery (i tried burn surgery too later, and after that i tried the health scanner too)
#### What actually happened
the Biopsy scanner scanned the limb, WITHOUT doing the surgery step.
#### Steps to reproduce
get a wounded (brute or burn) patient, open the incision using the scalpel, stop the bleeding with the hemostat (optional), fully open the incision using the retractor and try to use the Biopsy scanner (or the health scanner, the two wont work) and scan the patient, try to continue the surgery then notice that YOU DIDNT DID THE STEP, YOU SIMPLY SCANNED THE PATIENT NORMALLY EVEN AFTER DOING EVERYTHING TO SCAN HIM/HER.

#### Additional info:
Server revision: master - 2020-08-11
f5dd88d03688118359d1b29461fe1b2b008b2311
i belive that the bug is happening because of the "Health Analyzers work on all intent levels" Commit

**Comment by sds2413** [comment]
Created External Limb Surgery, and Autopsy Scanner Fix #1126 pull request to fix this issue. Both the health analyzer and biopsy scanner will allow you to fix burn or brute damage to limbs. They will also keep the normal scanning functionality.
