### ISSUE TITLE
Bitter Medicine advanced trauma kit

### ISSUE THREAD

**Issue by sds2413** [GeneriedJenelle/The-World-Server-Redux#1085]
#### Brief description of the issue

The bounty Bitter Medicine scans for whole stacks of advanced trauma kit not how many are in the stack.

#### What you expected to happen

A stack of five will add five to the bounty.

#### What actually happened

A stack of five will only show as adding one to the bounty.

#### Steps to reproduce

Insert advanced trauma kit into a bounty for Bitter Medicine

**Comment by GeneriedJenelle** [comment]
Yes, it doesn't account for stacks, just the number that you put into the bounty machine, this is normal.
