### ISSUE TITLE
Business Transation Data

### ISSUE THREAD

**Issue by sds2413** [GeneriedJenelle/The-World-Server-Redux#1097]
#### Brief description of the issue

Any one can print anyone Business Transation Data.

#### What you expected to happen

A password should be required to print out this data, as it has account information on in. Not of just the business, but its employees as well. 

#### What actually happened

You can open any business account and print out the account history.

#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by GeneriedJenelle** [comment]
Not a bug, unlike personal bank data business transactional data is within the public domain.
