### ISSUE TITLE
Amputated hands still show up in the side-view

### ISSUE THREAD

**Issue by XanderDox** [GeneriedJenelle/The-World-Server-Redux#127]
If you select full-arm amputation in character creation, from the side of your character it will appear as if they still have hands. Facing forwards or backwards however does not have this issue.

**Comment by Pygmali** [comment]
I don't think we can ever correct that, as any character clothing is made with a hole in place of the hand. So unless you fill that hole in each and every piece of clothing...

**Comment by XanderDox** [comment]
@Pygmali Aurora seems to have resolved this. Mass-Aurora clothing port? xD
