### ISSUE TITLE
Transfer Amount Issues, Salt, Pepper and Milk

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#221]
The salt and pepper shakers are apparently not giving an exact amount, neither are the milk cartons. People are coming off with things like 0.95, 1.09, and 37.4. Nothing seems to be exact. It could be on other things though I haven't tested it yet.

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@Electric` in `#bug-reports`.

**Comment by CentComOp** [comment]
Attempting to recreate didn't get unusual numbers with direct use. Due to how the game handles mixtures, however, if you get anything else inside your salt shaker, it'll them try and transfer <1 of all reagents inside the item. It's not _precisely_ a bug?
