### ISSUE TITLE
Clutchbag Lacks Sprite

### ISSUE THREAD

**Issue by McTashie** [GeneriedJenelle/The-World-Server-Redux#222]
#### Brief description of the issue
Clutchbag loadout item lacks a sprite. It spawns in your bag taking up bag space, but you are unable to remove and/or use the clutchbag.
#### What you expected to happen
To be able to see and use clutchbag.
#### What actually happened
Lost some bag space I'm not getting back.
#### Steps to reproduce
Spawn in with clutchbag loadout item equipped. (under accessories)
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
Server revision: master - 2019-02-08
bbbe77560331c2e5ed6f3a1cb7941ab2eb23c887 
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by uzername** [comment]
![Handbag_Pattern3 png 1ce9066984112f33b6fecf1b6180b804](https://user-images.githubusercontent.com/864126/58204782-b191fb00-7ce5-11e9-97db-211256aa0dc3.png)

Heyo

**Comment by GeneriedJenelle** [comment]
https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/450
