### ISSUE TITLE
Modular Computer Websites

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#295]
This is a bounty. If you wish to claim it, let me know so I can reserve it for you.

**Modular Websites**

Summary:
A modular computer program that allows you to browse "websites" in game. Websites are coded mainly via HTML and can contain variables from in-game. 

Features Desired:
- The ability to "Browse" and type in URL to browse another website.
- Refresh a page.
- Password protected sites
- Unique URLs, titles, and content which is var based in a datum, so it can be modified (only one instance of a website should exist, so if it's edited/changed, it should reflect from all computers.)
- **OPTIONAL:** The ability to add new websites and use paper BBcode to build and publish them.

**Mockup of concept:**
![image](https://user-images.githubusercontent.com/12565163/54965170-3cb17780-4f67-11e9-8aea-6ce87bab9e5c.png)

You don't need to code in the actual websites themselves, I can do that. Just a clean functional code would be appreciated. See https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/217 for an example.

Name your price on this one.

**Comment by Gh0sT2242** [comment]
I'll give it a go I suppose

**Comment by GeneriedJenelle** [comment]
https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/313

Bounty paid here.
