### ISSUE TITLE
Communicator List

### ISSUE THREAD

**Issue by Moonyman** [GeneriedJenelle/The-World-Server-Redux#31]
Communicators spawn multiple times in the contact list

![image](https://user-images.githubusercontent.com/12565163/51717256-18551f80-2038-11e9-9c61-0acc3a2c9be6.png)

**Comment by GeneriedJenelle** [comment]
Resolved here: https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/53

**Comment by GeneriedJenelle** [comment]
Fixed with new communicator update.
