### ISSUE TITLE
Airlocks cannot be constructed

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#357]
![image](https://user-images.githubusercontent.com/12565163/56669684-716d3780-66a9-11e9-8f8e-5aa4aa1398e5.png)

**Comment by CentComOp** [comment]
This one was simple yet odd; Is_Cable_Coil in door assembly is referenced, but cable coils are _not_ defined as valid for it. Requires a small edit to a couple files.

**Comment by GeneriedJenelle** [comment]
Thanks for the fix.
