### ISSUE TITLE
Children cry sound

### ISSUE THREAD

**Issue by Moonyman** [GeneriedJenelle/The-World-Server-Redux#36]
children cry uses adult cry sound

**Comment by Pygmali** [comment]
> 
> 
> children cry uses adult cry sound

Couldn't reproduce, @Moonyman,
Code wise, it seems good:
male_scream_sound		= 'sound/voice/human/boy_scream.ogg'
female_scream_sound = 'sound/voice/human/girl_scream.ogg'

For both Adolescent/childs, and the sounds used is boy/girl and not man/woman.

**Comment by GeneriedJenelle** [comment]
Ah, those are scream sounds (the sound you get when a police officer harmbatons a kid), there's cry sounds too (see emotes).

**Comment by Pygmali** [comment]
Gotcha, will work on that

**Comment by Pygmali** [comment]
Waiting for merge
