### ISSUE TITLE
Zombies able to buckle themselves and people (buckle combat)

### ISSUE THREAD

**Issue by McTashie** [GeneriedJenelle/The-World-Server-Redux#440]
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by McTashie** [comment]
I attempted to look into this buy looking at the normal buckle variables in game. can_buckle and buckle_lying specifically. With can_buckle = 0 the player could buckle/unbuckle. Same with 1, -1, and I even tried 'false'. They could buckle.unbuckle each time. When looking at buckle_lying it was at = -1. The player could still buckle while lying down. Same thing with 0, 1, and 'false'. 

The buckle_lying has been abused in the past by players buckling away from a cops attempt to grab and cuff them, as it cancels the grab.

**Comment by CentComOp** [comment]
Hello! Buckling is a strange beast in the code; "can_buckle" is actually (I believe) in reference to if an object is capable of being buckled on. Why it'd be on mobs as well is unclear. 

As to zombies being able to buckle, there are actually very few buckle limitations (assuming drag to chair). Mice, maint drones, and even the AI can buckle (assuming a chair is placed RIGHT next to the actual core). The nigh-sole exception is the pAI, and it'd be possible to work off that to add the Zombie role to being unable to drag-buckle. However, they could still Grab-> Buckle, but that also has a 'doing things' bar that may help balance it out.

Would that be sufficient?

**Comment by McTashie** [comment]
Currently the buckle combat from zombies is an issue, as well as downed players buckling themselves away from the arresting officers grab. I played with several things and tried to get it where players are unable to buckle with resting/on the ground, but was unable to figure it out. 

As for the zombies, grab/buckle with a progress bar would be a great fix, as itd prevent the zombie from buckle combating people.

**Comment by CentComOp** [comment]
I'll keep looking at the buckle stuff in general, trying to get used to Git again as well. I'll submit a pull request when I can.

**Comment by GeneriedJenelle** [comment]
Thanks for this.
