### ISSUE TITLE
General Windoor Access Issues

### ISSUE THREAD

**Issue by SilverTalismen** [GeneriedJenelle/The-World-Server-Redux#504]
#### Brief description of the issue
Most area's, such as Botany, have Windoors that are general access, letting anyone get in and for instance, toss all of the eggs you've made into the streets or steal things.
#### What you expected to happen
To be secure in my own workplace
#### What actually happened
Stepped away for a few minutes and have a half hour of of eggs being harvested tossed into the street
#### Steps to reproduce
Work in the Bar or kitchen or most areas with Windoors into your workplace.
Watch as you realize you have no workplace security.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by GeneriedJenelle** [comment]
Most of these have been resolved.
