### ISSUE TITLE
Cash

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#512]
#### Brief description of the issue
Cash does not split correctly when used.
#### What you expected to happen
Use 5, 10, 20, etc notes on cash registers or be able to split them.
#### What actually happened
They stay the same.
#### Steps to reproduce
Click on any single note, or try using that note on a register.
#### Additional info:
 - **Server Revision**: Found using the "Show Server Revision" verb under the OOC tab.
 - **Anything else you may wish to add** (Location if it's a mapping issue, etc)

**Comment by dapocalypse** [comment]
Im unable to replicate this.

**Comment by GeneriedJenelle** [comment]
Fixed with https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/771
