### ISSUE TITLE
Odd runtimes in AI/watermob interaction

### ISSUE THREAD

**Issue by UndeadNappist** [GeneriedJenelle/The-World-Server-Redux#555]
[2019-09-14T20:43:48] Runtime in mouse.dm,62: BYOND Error: bad instruction: 1282
  Caught by process: mob
  src: (the shallow water) (105,89,1) (/turf/simulated/floor/water) ()
  src.loc: (the shallow water) (105,89,1) (/turf/simulated/floor/water) ()
[2019-09-14T20:43:58] Runtime in mouse.dm,62: BYOND Error: bad instruction: 1282
  Caught by process: mob
  src: (the plating) (123,90,1) (/turf/simulated/floor) ()
  src.loc: (the plating) (123,90,1) (/turf/simulated/floor) ()
[2019-09-14T20:44:22] Runtime in mouse.dm,62: BYOND Error: bad instruction: 1282
  Caught by process: mob
  src: (the shallow water) (155,106,1) (/turf/simulated/floor/water) ()
  src.loc: (the shallow water) (155,106,1) (/turf/simulated/floor/water) ()

**Comment by UndeadNappist** [comment]
probably has to do with water being coded to make an overlay for mobs when they walk into it instead of using dual sprite overlays or something, but mice can't have it properly applied

**Comment by GeneriedJenelle** [comment]
resolved
