### ISSUE TITLE
Overlay related runtimes

### ISSUE THREAD

**Issue by UndeadNappist** [GeneriedJenelle/The-World-Server-Redux#556]
[2019-09-14T21:07:06] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (177,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (177,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (177,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (177,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:06] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (178,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (178,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (178,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (178,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:06] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (180,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (180,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (180,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (180,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:06] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (181,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (181,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (181,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (181,9,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:06] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (174,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (174,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (174,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (174,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:07] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (177,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (177,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (177,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (177,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:07] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (181,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (181,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (181,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (181,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:07] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (184,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (184,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (184,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (184,10,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:07] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (173,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (173,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (173,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (173,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))
  Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
  Atoms (/datum/controller/subsystem/atoms): Initialize(148228)
  Master (/datum/controller/master): Initialize(10, 0)
[2019-09-14T21:07:07] Runtime in wall_types.dm,214: BYOND Error: bad instruction: 4255
  proc name: auto join (/turf/simulated/shuttle/wall/proc/auto_join)
  src: the wall (177,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner)
  call stack:
  the wall (177,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner): auto join()
  the wall (177,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner): initialize(1)
  Atoms (/datum/controller/subsystem/atoms): InitAtom(the wall (177,11,3) (/turf/simulated/shuttle/wall/dark/hard_corner), /list (/list))

**Comment by GeneriedJenelle** [comment]
Can't recreate, know when this came up?

**Comment by UndeadNappist** [comment]
On game start, I believe? Although it was awhile ago and I may have used the forced start command.

**Comment by GeneriedJenelle** [comment]
Can't recreate, might be due to the game starting before the objects/atoms controller has started.
