### ISSUE TITLE
Fix police guns not firing

### ISSUE THREAD

**Issue by lardf** [GeneriedJenelle/The-World-Server-Redux#68]
I was in a huge fight with an armed person and I had no more nonlethals so I pulled my gun out and tried to fire it, it didn't fire, I checked if it had a magazine and it did, so I kept trying to fire and I saw that it uses ammo but it doesn't do jack shit, it eats up ammo but it doesn't actually fire. Please fix.

**Comment by lardf** [comment]
okay apparently that only happened on one round for only me. I don't know what happened there though.

**Comment by GeneriedJenelle** [comment]
I'll keep an eye out if anyone else reports this happening again. If this happens again to you, let me know.
