### ISSUE TITLE
Billboard examine icon bug

### ISSUE THREAD

**Issue by Myoblongvagooglia** [GeneriedJenelle/The-World-Server-Redux#750]
#### Brief description of the issue
When you right click on a billboard, it'll preview an anesthetic tank, instead of the proper icon.

#### What you expected to happen
To see a billboard.

#### What actually happened
I didn't see a billboard.

#### Steps to reproduce
Right click on any billboard.

#### Additional info:
![image](https://user-images.githubusercontent.com/53440643/71704220-fcf5a700-2da6-11ea-96ef-adef38daf239.png)

**Comment by GeneriedJenelle** [comment]
I can't recreate this. I think this may be one of those one-off compile errors that happens when DM does a shoddy compile (usually results in minor icon quirks that go away until it compiles again). 

Can you confirm if this is still a thing?
