### ISSUE TITLE
Hand teleporters teleport people to Centcom level into the sky

### ISSUE THREAD

**Issue by GeneriedJenelle** [GeneriedJenelle/The-World-Server-Redux#85]
Ideally, would like it to teleport people to the same z level they originated on.

**Comment by MadmanMartian** [comment]
Working on a fix for this, but BountySource is being a pain trying to sign up for.

**Comment by GeneriedJenelle** [comment]
https://github.com/GeneriedJenelle/The-World-Server-Redux/pull/250
