### ISSUE TITLE
Cannot Construct Windoors

### ISSUE THREAD

**Issue by Leganoth** [GeneriedJenelle/The-World-Server-Redux#989]
**Issue:** Windoors cannot be constructed. Selecting "Windoor" from the _reinforced glass sheets_ popup menu results in a _windoor_ item that can be picked up and thrown (possibly bagged? did not test), but will not under any circumstances function as a barrier.

**Expectation:** Upon using x15 _reinforced glass sheets_, I expected to be able to interact with one of an Engineer's standard items - such as a screwdriver or welder, to then construct a functioning _windoor_.

**Result:** No interaction occurred with any but one tool, regardless of whether the _windoor_ was in a hand or on the ground. The exception is using a wrench on the _windoor_, which will result in the _windoor_ being disassembled and x4 _steel sheets_ being left instead of the x15 _reinforced glass sheets_ that were used to create it in the first place.

**-Additional Info-**
**Server revision:** master - 2020-04-17; 637a8a97c3ff803f5f04ff6c0d84c496b3f11061 
**Location:** Creation of windoor attempted in Chemistry, as well as Engineering Lobby.

**Comment by GeneriedJenelle** [comment]
Not a bug, that is a windoor frame. You must turn to your building direction and click on it in your hands to build it.

**Comment by Leganoth** [comment]
ghsdfkjg My bad! Thank you.
